import type { Metadata } from "next";
import { Manrope, Caveat, Nunito } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import BaseLayout from "./components/BaseLayout";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${manrope.variable} ${caveat.variable} ${nunito.variable} antialiased`}
      >
        <BaseLayout>
          {children}
        </BaseLayout>
        <Script
          src="https://unpkg.com/aos@2.3.1/dist/aos.js"
          strategy="beforeInteractive"
        />
        <Script id="aos-init" strategy="afterInteractive">
          {`
            if (typeof AOS !== 'undefined') {
              AOS.init({
                duration: 1000,
                once: true,
                offset: 100
              });
            }
          `}
        </Script>
      </body>
    </html>
  );
}
